// Database types for Furtim Stealth Address Payment System
// This file will be auto-generated by Supabase CLI

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          username: string;
          wallet_address: string;
          pin_hash: string;
          public_key: string | null;
          email: string | null;
          phone: string | null;
          profile_image_url: string | null;
          bio: string | null;
          location: string | null;
          website: string | null;
          twitter_handle: string | null;
          created_at: string;
          updated_at: string;
          last_login: string | null;
          is_active: boolean;
          is_verified: boolean;
          verification_token: string | null;
          password_reset_token: string | null;
          password_reset_expires: string | null;
          two_factor_enabled: boolean;
          two_factor_secret: string | null;
          login_attempts: number;
          locked_until: string | null;
          metadata: any;
        };
        Insert: {
          id?: string;
          username: string;
          wallet_address: string;
          pin_hash: string;
          public_key?: string | null;
          email?: string | null;
          phone?: string | null;
          profile_image_url?: string | null;
          bio?: string | null;
          location?: string | null;
          website?: string | null;
          twitter_handle?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          is_active?: boolean;
          is_verified?: boolean;
          verification_token?: string | null;
          password_reset_token?: string | null;
          password_reset_expires?: string | null;
          two_factor_enabled?: boolean;
          two_factor_secret?: string | null;
          login_attempts?: number;
          locked_until?: string | null;
          metadata?: any;
        };
        Update: {
          id?: string;
          username?: string;
          wallet_address?: string;
          pin_hash?: string;
          public_key?: string | null;
          email?: string | null;
          phone?: string | null;
          profile_image_url?: string | null;
          bio?: string | null;
          location?: string | null;
          website?: string | null;
          twitter_handle?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          is_active?: boolean;
          is_verified?: boolean;
          verification_token?: string | null;
          password_reset_token?: string | null;
          password_reset_expires?: string | null;
          two_factor_enabled?: boolean;
          two_factor_secret?: string | null;
          login_attempts?: number;
          locked_until?: string | null;
          metadata?: any;
        };
      };
      // Add other table types as needed
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
